# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)

1.19.5


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [11]:
n = np.zeros((1,4,3))
print("%d bytes" % (n.size * n.itemsize))

96 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
#print(np.__doc__)

def print_doc_numpy():
    print(np.__doc__)

print_doc_numpy()


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
x = np.zeros(10)
print(x)
x[4] = 1
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [21]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [27]:

vector = np.arange(10)
vector = vector[::-1]
print(vector)

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [34]:
arr = np.array( [1,2,0,0,4,0] )
print(np.where(arr == 0)[0])

[2 3 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [36]:
print(np.identity(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [37]:
x = np.random.random((3,3,3))
print(x)


[[[0.3683364  0.33930585 0.64195916]
  [0.02524296 0.62541903 0.60087746]
  [0.19596197 0.61805882 0.23055984]]

 [[0.49680974 0.93224533 0.67284699]
  [0.00403806 0.20428694 0.75305028]
  [0.1242747  0.53098859 0.27185701]]

 [[0.23095235 0.01887741 0.85657128]
  [0.47765889 0.66278763 0.99431336]
  [0.92469895 0.34399382 0.28661763]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [46]:
x = np.random.random((10,10))
#print(x)
print("min=",x.min())
print("max=",x.max())


min= 0.0038089961559872876
max= 0.9976060555512412


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
x = np.random.random((30))
#print(x)
print("mean = ", x.mean())

mean =  0.5655131736290567


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
n = 7  #size
x = np.ones((n,n))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [56]:
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [70]:
# explanation: NaN means not a number. 

# 0 * np.nan
# Answer:nan 
# explanation: unknown(nan) mulitiplied with nan is unknown(nan)

# np.nan == np.nan
# Answer:False
# Explanation:  This is because equivalence between missing 
#      or invalid values is not well defined. In practice, this behavior 
#      prevents silent bugs from creeping into your program. 
#     simply, it is by definition false.¯\_(ツ)_/¯. 

# np.inf > np.nan
# Answer: False 
# Explanation: inf - is infinity - a value that is greater than any other value. 
#          again, " nan " stands for Not A Number. comparing nan with a number,
#          returns False.

# np.nan - np.nan
# Answer:nan
# explanation: unknown(nan) subtracted with unknown(nan) is an unknown(nan)

# np.nan in set([np.nan])
# Answer: True
# explanation: np.nan is present inside np.nan and it is unique

# 0.3 == 3 * 0.1
# Answer: False
# Explanation: try print(0.3) and print(0.1*3) = 0.30000000000000004
# ¯\_(ツ)_/¯

0.3
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [76]:
x = np.diag(1+np.arange(4), k = -1)
print(x)
# print(1+np.arange(4))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[1 2 3 4]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [80]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [85]:
# 6*7*8  =336
print (np.unravel_index(100, (6,7,8)))
# print (np.unravel_index(0, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
array= np.array([[0,1], [1,0]])
x = np.tile(array,(4,4))   # 16 * 4 =64, this 4 ([0,1],[1,0])
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
x = np.random.random((5,5))
maximum = x.max()
minimum = x.min()
x= (x-maximum)/(maximum-minimum)   # normalise formuala
print (x)



[[-0.89776242 -0.30904012 -0.32134391 -0.41404624 -0.47324848]
 [-0.92792631 -0.67352236  0.         -0.59843114 -0.67425622]
 [-0.68443082 -0.85309599 -0.66240028 -0.44347539 -0.18239689]
 [-0.63975721 -1.         -0.78645813 -0.87703793 -0.6943931 ]
 [-0.13964421 -0.90640388 -0.83772739 -0.23723487 -0.12841914]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [99]:
# help(np.dtype)
# ubyte = unsigned bytes, dtype = datatype  
color_datatype = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color_datatype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-99-4cdb32b01e6e>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color_datatype = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [103]:
x = np.random.random(15).reshape((5,3))
y = np.random.random(6).reshape((3,2))
print(np.dot(x,y))  # this will print 5,2 matrix 


[[0.52906017 0.67111381]
 [0.639937   0.78170267]
 [0.33919219 0.50439404]
 [0.77188314 0.7257678 ]
 [0.76152625 0.59018411]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [108]:
x = np.arange(10)
x[(x >= 3) & (x <= 8)] = -1
print(x) #if the positions are little different then need to change number a bit.


[ 0  1  2 -1 -1 -1 -1 -1 -1  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [114]:
# Answer: 9 10 
# Explanation:  Python's sum signature starts with 0. 
#           Numpy must be redefining range, and
#           it has different boundry rules. 
# The first line is equivalent to 0+1+2+3+4+(-1). 
# The third line is equivalent to 0+1+2+3+4 on axis=-1
# interestingly, it happens only one time.

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [157]:
# z power z 
Z = np.arange(4)
print(Z**Z) # legal 

# bit shifting operations
Z = np.arange(10)
print(Z)   # shift to left by 5 bits
           # shift to right by 5 bits
#a = bin(0b1111 << 2)
#print(a)
#a = bin(0b1111 >> 2)
#print(a)

print(2 << Z >> 2)   # legal

print(1j*Z)  # legal, make it as a imaginary num.
print(Z/1/1)   # legal, it turns to float
print(Z <- Z)   # legal
#print(Z < Z > Z) # illegal value error  

[ 1  1  4 27]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   4   8  16  32  64 128 256]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[False False False False False False False False False False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [169]:
#np.array(0) / np.array(0)
# Ans: zero by zero -> not a number

# np.array(0) // np.array(0)
# Ans:0, floor division or integer division.

# np.array([np.nan]).astype(int).astype(float)
# Ans:array([-9.22337204e+18]) returns a long floating point number if we conveert

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [173]:
num = np.random.random(4)
print(num)
print(np.round(num,0))

[0.67184953 0.84982628 0.26055381 0.11134841]
[1. 1. 0. 0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [174]:
ar1 = np.array([0, 1, 2, 3, 4]) 
ar2 = [1, 3, 4] 
  
# Common values between two arrays 
print(np.intersect1d(ar1, ar2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [176]:
# np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [178]:
# nope, False
# Explanations: 
# print(np.sqrt(-1))  --> nan
# print(np.emath.sqrt(-1))  --> 1i   j = sqrt(-1) emath frameworks 


1j



#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [184]:
# time delta makes to convert the convensions todo arithmetic operations on datetime
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-03-21
Today:  2021-03-22
Tomorrow:  2021-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [186]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
# form staring of 07 to before starting of 08
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [191]:
A = np.ones(1)*1
B = np.ones(1)*2
C = np.ones(1)*3 

print(A,B,C)  # operations: (1+2) * (-1/2) --> -3 *0.5
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[1.] [2.] [3.]
[3.]
[0.5]
[-0.5]
[-1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [211]:
num = np.random.uniform(-10, +10, 3)  # ranges and no. of randoms
print(num)
#Method 1:   
print(num.astype(np.int32))

#Method 2:
#print(type(np.trunc(num)))
print(np.trunc(num))

# Method 3:
print(np.floor(num))

# Method 4:
print(np.ceil(num))

# Method 5:
print(random.randint(-10,10,3))

[ 8.28139258 -5.27876327 -4.81041917]
[ 8 -5 -4]
[ 8. -5. -4.]
[ 8. -6. -5.]
[ 9. -5. -4.]
[0 7 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [218]:
x = np.zeros((5, 5))
print(x)
x += np.arange(0,5) 

print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [234]:
def generator_func():
    list_1 = (a for a in range(10))
    return list_1
    
print(np.fromiter(generator_func(),int))
    

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [239]:
vector1 = np.linspace(start=0, stop=1, num=10, endpoint=False)
vector2 = np.random.random(10)
print(vector1)
print(vector2)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.37620029 0.54206162 0.2272266  0.14048979 0.29422588 0.42044656
 0.86037227 0.92488437 0.58260405 0.52041984]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [246]:
vector2 = np.random.random(10)
vector3 = np.sort(vector2)
print(vector3)

[0.21669255 0.21693846 0.26091325 0.38707316 0.45023402 0.46307272
 0.46880695 0.47280928 0.48334948 0.63045976]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [263]:
import time
x1 = np.arange(1000000)
x2 = np.arange(100)


begin_time = time.time()
y1 = np.sum(x1)
end_time = time.time()
print("timetaken for np.sum",str(1000*(end_time - begin_time)))

begin_time2 = time.time()
y2 = sum(x1)
end_time2 = time.time()
print("timetaken for normal sum",str(1000*(end_time2 - begin_time2)))


begin_time3 = time.time()
y3 = np.sum(x2)
end_time3 = time.time()
print("timetaken for np.sum",str(1000*(end_time3 - begin_time3)))

begin_time4 = time.time()
y4 = sum(x2)
end_time4 = time.time()
print("timetaken for normal sum",str(1000*(end_time4 - begin_time4)))


timetaken for np.sum 2.056598663330078
timetaken for normal sum 2.1164417266845703
timetaken for np.sum 0.2727508544921875
timetaken for normal sum 0.2353191375732422


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [372]:
A = random.randint(-100,100,10)
B = random.randint(-100,100,10)
print(A,"\n",B)
print(np.array_equal(A, B))


[ 80   0  28  23 -25 -27 -24 -61  72  17] 
 [-15  90  56 -36 -96 -42 -87  40 -79  38]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [274]:
A = random.randint(-100,100,10)
A.flags.writeable = False

#A[1] = 1   could not change value

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [278]:
# np.sqrt, np.arctan2
Rand_num = np.random.random((10, 2))
print(Rand_num)

X, Y = Rand_num[:, 0], Rand_num[:, 1]  #multiple assginment x= [:,0]all elements in col 0 is equal to x

# To convert from Cartesian Coordinates (x,y) to Polar Coordinates (r,θ):
# r = √ ( x2 + y2 )
# θ = tan-1 ( y / x ) 

# Calculating radius
radius = np.sqrt(X ** 2 + Y ** 2)  
# Calculating angle (theta) in radian
theta = np.arctan2(Y, X)
print("In polar:")
print(radius)
print(theta)

[[0.82174076 0.19630315]
 [0.0909344  0.35037843]
 [0.72389877 0.38213189]
 [0.50395404 0.28058738]
 [0.50777005 0.43457109]
 [0.46899936 0.38844117]
 [0.35955586 0.58678773]
 [0.38175099 0.92080781]
 [0.9196043  0.86448434]
 [0.20343851 0.76752599]]
In polar
[0.84486259 0.36198634 0.81856839 0.57680062 0.66834307 0.60897203
 0.68818621 0.99680531 1.26214311 0.79402983]
[0.23449229 1.31686672 0.48570226 0.50802738 0.70787606 0.69172122
 1.02105246 1.1777822  0.75451268 1.31169688]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [295]:
x = np.random.random((10))
print("orig\n",x)
x[x == np.max(x)] = 0
print(x)

A = random.randint(-100,100,10)
print("orig\n",A)
A[A.argmax()] = 0
print(A)

orig
 [0.49343487 0.91607429 0.87007022 0.00423035 0.83933864 0.548661
 0.74703844 0.73750165 0.22791073 0.44529296]
[0.49343487 0.         0.87007022 0.00423035 0.83933864 0.548661
 0.74703844 0.73750165 0.22791073 0.44529296]
orig
 [ 53  81 -67 -49  23  45   5  74 -50  53]
[ 53   0 -67 -49  23  45   5  74 -50  53]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [304]:
def struc_Array(x,y):
    A = np.zeros((x,y), [('x',float),('y',float)])
    print(A)
    A['x'], A['y'] = np.meshgrid(np.linspace(0,1,x),np.linspace(0,1,y))
    print(A)

struc_Array(2,2)


[[(0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.)]]
[[(0., 0.) (1., 0.)]
 [(0., 1.) (1., 1.)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [312]:
                                   # Compute the determinant of an array.

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)  # subtract outer produces more dimensions                           
print(X)
print(Y)
print("====C====")
print(C)
print("determinant",np.linalg.det(C))    

#x = np.random.random((5, 5))
#y = np.random.random((5, 5))
#c = 1 / (x - y)
#c = 1 / np.subtract.outer(x, y)
3a =np.linalg.det(c)
#print("a",a)

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
====C====
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
determinant 3638.1636371179666
a [[-3.36442530e+05 -7.94454561e+05 -5.62210135e+04 -6.19983311e+06
   4.27768062e+06]
 [-4.02557747e+07 -6.64963670e+07 

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [320]:
for dtype in [np.int8, np.int32, np.int64]:
    print("min of ", dtype,  np.iinfo(dtype).min)
    print("max of ", dtype, np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print("min of ", dtype, np.finfo(dtype).min)
    print("max of ", dtype, np.finfo(dtype).max)
    print("eps of ", dtype, np.finfo(dtype).eps)
    
    #iinfo    The equivalent for integer data types.  eps= epsilon




min of  <class 'numpy.int8'> -128
max of  <class 'numpy.int8'> 127
min of  <class 'numpy.int32'> -2147483648
max of  <class 'numpy.int32'> 2147483647
min of  <class 'numpy.int64'> -9223372036854775808
max of  <class 'numpy.int64'> 9223372036854775807
min of  <class 'numpy.float32'> -3.4028235e+38
max of  <class 'numpy.float32'> 3.4028235e+38
eps of  <class 'numpy.float32'> 1.1920929e-07
min of  <class 'numpy.float64'> -1.7976931348623157e+308
max of  <class 'numpy.float64'> 1.7976931348623157e+308
eps of  <class 'numpy.float64'> 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [344]:
b = np.arange(25).reshape(5, 5) 
print("\nIs NaN: \n", np.isnan(b)) 
c = [[1,2,3],[np.nan,2,2]] 
print("\nIs NaN: \n", np.isnan(c)) 
np.set_printoptions(edgeitems=3,infstr='inf',linewidth=75, nanstr='nan', precision=8,suppress=False, threshold=1000, formatter=None)
print("\nc\n",c)


Is NaN: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]

Is NaN: 
 [[False False False]
 [ True False False]]

c
 [[1, 2, 3], [nan, 2, 2]]

c
 [[1, 2, 3], [nan, 2, 2]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [371]:
 Z = np.arange(100)
v = np.random.uniform(0,100)                         
index = (np.abs(Z-v)).argmin()             #
print("z",Z)
print("v",v)
print("index",index)
print("closest value:", Z[index])



v 14.665846416211913
z [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
index 15
closest value: 15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [350]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]                  # say for example row 0 and 1 to swap
print(A)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [362]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)             # say window =3, cumsum is cumulative sum and stored in list     
    ret[n:] = ret[n:] - ret[:-n]                # list of upto the window level:, subtracted with next window 
    return ret[n - 1:] / n

ran_list1 = np.arange(10)
ran_list2 = random.randint(-100,100,10)
print(moving_average(ran_list1, n=3))
print(moving_average(ran_list2, n=4))



[1. 2. 3. 4. 5. 6. 7. 8.]
[ 19.75  50.25  13.25 -11.5  -37.25 -42.5  -24.25]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)